[project]
name = "flipflop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pyright>=1.1.411",
    "ruff>=0.16.2",
]

[tool.ruff]
target-version = "py313"

[tool.pyright]
pythonVersion = "3.13"
venvPath = "."
venv = ".venv"
